/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Window Control
 #	author : miyako
 #	2016/02/09
 #
 # --------------------------------------------------------------------------------*/



// --- Window Control
void WND_Is_minimized(sLONG_PTR *pResult, PackagePtr pParams);
void WND_Is_maximized(sLONG_PTR *pResult, PackagePtr pParams);
void WND_SET_TITLE(sLONG_PTR *pResult, PackagePtr pParams);
void WND_Get_title(sLONG_PTR *pResult, PackagePtr pParams);
void WND_USE_ICON_FILE(sLONG_PTR *pResult, PackagePtr pParams);
void WND_MAXIMIZE(sLONG_PTR *pResult, PackagePtr pParams);
void WND_MINIMIZE(sLONG_PTR *pResult, PackagePtr pParams);
void WND_RESTORE(sLONG_PTR *pResult, PackagePtr pParams);
void WND_SET_POSITION(sLONG_PTR *pResult, PackagePtr pParams);
void WND_GET_POSITION(sLONG_PTR *pResult, PackagePtr pParams);
